import factors
print("---------------------------")
print("........ Version 2.7.......")
print("---------------------------")
n=int(raw_input("Enter the number:"))
print("Number of Factors for %d is" %n,factors.nfact(n))
print("Sum of Factors for %d is" %n,factors.sfact(n))
print("Factors for %d is" %n,factors.fact(n))
print("Even Factors for %d is" %n,factors.efact(n))
print("Odd Factors for %d is" %n,factors.ofact(n))
print("Prime Factors for %d is" %n,factors.pfact(n))
print("Even Prime Factors for %d is" %n,factors.epfact(n))
print("Sum of Even Factors for %d is" %n,factors.sum_efact(n))
print("Sum of Odd Factors for %d is" %n,factors.sum_ofact(n))
print("Sum of Prime Factors for %d is" %n,factors.sum_pfact(n))
